trigger:
  branches:
    include:
    - main

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/EctBlazorApp.Server.csproj'
        #feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Restore ServerTests project
      inputs:
        command: 'restore'
        projects: '**/EctBlazorApp.ServerTests.csproj'
    - task: DotNetCoreCLI@2
      displayName: Restore ClientTests project
      inputs:
        command: 'restore'
        projects: '**/EctBlazorApp.ClientTests.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/EctBlazorApp.Server.csproj'
    - task: DotNetCoreCLI@2
      displayName: Run Server UTs
      inputs:
        command: 'test'
        projects: '**/EctBlazorApp.ServerTests.csproj'
    - task: DotNetCoreCLI@2
      displayName: Run Blazor components UTs
      inputs:
        command: 'test'
        projects: '**/EctBlazorApp.ClientTests.csproj'

    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        Contents: |
          **\*.dll
          **\*.runsettings
          **\*.csproj
        TargetFolder: '$(build.ArtifactStagingDirectory)'
    - task: DotNetCoreCLI@2
      displayName: Publish solution
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
        PathtoPublish: '$(build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'