trigger:
  branches:
    include:
    - main

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/EctBlazorApp.Server.csproj'
    - task: DotNetCoreCLI@2
      displayName: Run Tests
      inputs:
        command: 'test'
        projects: '**/EctBlazorApp.ServerTests.csproj'

- stage: Release  
  displayName: Release stage

  jobs:
  - job: Release
    displayName: Release to Azure

    pool:
        vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/EctBlazorApp.Server.csproj'
        
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(3c7c2ff0-247b-475b-b3ec-932545c61100)'
        appType: 'webApp'
        WebAppName: 'ect'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'