trigger:
  branches:
    include:
    - main

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/EctBlazorApp.Server.csproj'
        #feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Restore ServerTests project
      inputs:
        command: 'restore'
        projects: '**/EctBlazorApp.ServerTests.csproj'
    - task: DotNetCoreCLI@2
      displayName: Restore ClientTests project
      inputs:
        command: 'restore'
        projects: '**/EctBlazorApp.ClientTests.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/EctBlazorApp.Server.csproj'
    - task: DotNetCoreCLI@2
      displayName: Run Server UTs
      inputs:
        command: 'test'
        projects: '**/EctBlazorApp.ServerTests.csproj'
    - task: DotNetCoreCLI@2
      displayName: Run Blazor components UTs
      inputs:
        command: 'test'
        projects: '**/EctBlazorApp.ClientTests.csproj'

  - stage: Release  
    displayName: Release stage

    jobs:
    - job: Release
      displayName: Release to Azure

      pool:
          vmImage: $(vmImageName)
      steps:
      - task: UseDotNet@2
        displayName: Force .NET 5
        inputs:
          packageType: 'sdk'
          version: '5.x'
      - task: DotNetCoreCLI@2
        displayName: Restore project
        inputs:
          command: 'restore'
          projects: '**/EctBlazorApp.Server.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: Publish project
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/EctBlazorApp.Server.csproj'
      - task: AzureRmWebAppDeployment@4
        displayName: Deploy to Azure
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure for Students(3c7c2ff0-247b-475b-b3ec-932545c61100)'
          appType: 'webApp'
          WebAppName: 'ect'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'