// <auto-generated />
using System;
using EctBlazorApp.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EctBlazorApp.Server.Migrations
{
    [DbContext(typeof(EctDbContext))]
    [Migration("20210224111630_MarginForNotification")]
    partial class MarginForNotification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttendeesAsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EctUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Organizer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EctUserId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.CommunicationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CommunicationPoints");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.EctAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.EctTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LeaderId")
                        .HasColumnType("int");

                    b.Property<int>("MarginForNotification")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.EctUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSignIn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MemberOfId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberOfId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.ReceivedMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EctUserId")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EctUserId");

                    b.ToTable("ReceivedEmails");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.SentMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EctUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientsAsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EctUserId");

                    b.ToTable("SentEmails");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.CalendarEvent", b =>
                {
                    b.HasOne("EctBlazorApp.Shared.Entities.EctUser", null)
                        .WithMany("CalendarEvents")
                        .HasForeignKey("EctUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.EctAdmin", b =>
                {
                    b.HasOne("EctBlazorApp.Shared.Entities.EctUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.EctTeam", b =>
                {
                    b.HasOne("EctBlazorApp.Shared.Entities.EctUser", "Leader")
                        .WithMany("LeaderOf")
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.EctUser", b =>
                {
                    b.HasOne("EctBlazorApp.Shared.Entities.EctTeam", "MemberOf")
                        .WithMany("Members")
                        .HasForeignKey("MemberOfId");
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.ReceivedMail", b =>
                {
                    b.HasOne("EctBlazorApp.Shared.Entities.EctUser", null)
                        .WithMany("ReceivedEmails")
                        .HasForeignKey("EctUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EctBlazorApp.Shared.Entities.SentMail", b =>
                {
                    b.HasOne("EctBlazorApp.Shared.Entities.EctUser", null)
                        .WithMany("SentEmails")
                        .HasForeignKey("EctUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
